### ISSUE TITLE
Add version flag

### ISSUE THREAD

**Issue by NCrashed** [Jebbs/DSFML#163] opened 2015-03-07 10:21 UTC
Topic: https://github.com/D-Programming-Language/dub/wiki/Version-management#deprecation-of-branch-based-dependencies

To stop receiving following message while using DSFML:
```
WARNING: A deprecated branch based version specification is used for the dependency dsfml. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
```

**Comment by Jebbs** [comment] 2015-03-07 17:10
Duplicate of this one: https://github.com/Jebbs/DSFML/issues/132

Also, classes are almost at an end for me for the term, and during my break I should have a new version of DSFML ready which will fix this.

**Closed by Jebbs** 2015-03-07 17:10 UTC
Labels: duplicate
