### ISSUE TITLE
Link error with DSFML 2.3

### ISSUE THREAD

**Issue by ghost** [Jebbs/DSFML#241] opened 2016-12-28 23:22 UTC
Hello,

when I execute dub ([basic code](http://dsfml.com/docs/firstprogram.html#used-code)) with DSFML 2.3, I get this error:
```
$ dub
WARNING: A deprecated branch based version specification is used for the dependency dsfml. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
Performing "debug" build using dmd for x86_64.
dsfml:system ~2.3: target for configuration "library" is up to date.
dsfml:audio ~2.3: target for configuration "library" is up to date.
dsfml:window ~2.3: target for configuration "library" is up to date.
dsfml:graphics ~2.3: target for configuration "library" is up to date.
dsfml:network ~2.3: target for configuration "library" is up to date.
dsfml ~2.3: target for configuration "library" is up to date.
dsfml_test ~master: building configuration "application"...
Linking...
/usr/bin/ld: .dub/build/application-debug-linux.posix-x86_64-dmd_2072-CA42226E17993BE0B3219E91D1E90827/dsfml_test: hidden symbol ' __cpu_model » in /usr/lib/gcc/x86_64-linux-gnu/5/libgcc.a(cpuinfo.o) is referenced by DSO
/usr/bin/ld : final link failed: Bad value
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
dmd failed with exit code 1.
$
```

Any Ideas ?

Maybe, how to apply [this patch](http://stackoverflow.com/questions/38727800/ld-linker-error-cpu-model-hidden-symbol) to CSFML ?

**Comment by Jebbs** [comment] 2016-12-28 23:34
Huh that's strange. Does this happen for you with SFML too? And if you apply that patch yourself does it fix your problem?

**Comment by LucienPe** [comment] 2016-12-30 00:22
With SFML I don't have any problem, with and without applying the patch by myself.
I'll try some tests with CSFML, maybe it's a CSFML issue.

**Comment by Jebbs** [comment] 2016-12-30 05:41
But if you patch DSFMLC does it fix this?

**Comment by LucienPe** [comment] 2016-12-30 10:00
CSFML works well, any linker error ([project](https://mega.nz/#!JBNDDR5Z!ks0wzDSwdBRxAjg0PbwJ44pko86EFFMq_LCwftATPeQ)).
It's definitively a DSFML(C) issue.
Does DSFML 2.3 work for you ?

**Comment by Jebbs** [comment] 2016-12-30 15:20
2.3 hasn't been officially released. I haven't tested it on Linux yet, so I don't know. What distro are you using?

**Comment by LucienPe** [comment] 2016-12-30 19:31
I'm using Ubuntu 16.04 x64 with dmd.
When building DSFML from source with unit tests we have the same issue.
```
git clone -b 2.3 https://github.com/Jebbs/DSFML.git DSFML
cd DSFML
dmd build.d && ./build -unittest
```

**Comment by Jebbs** [comment] 2016-12-31 01:22
Ok, thanks. I'll look into this. Will hopefully have something for you soon.

**Comment by Jebbs** [comment] 2018-08-21 16:49
Going to close this as it is actually a gcc bug caused by `stb_image`.

It shouldn't affect DSFML anymore anyway as the library was changed to run on top of SFML.

**Closed by Jebbs** 2018-08-21 16:49 UTC
